theme: jekyll-theme-minimal
title: Esther XU FEI
description: Applied Scientist III, Amazon.com, Inc.<br>Seattle, WA<br><br><a href="./CV/main.pdf">CV</a> | <a href="https://scholar.google.com/citations?user=YOUR_ID">Google Scholar</a> | <a href="https://github.com/Estherrrrrxu">GitHub</a> | <a href="https://www.linkedin.com/in/estherxufei/">LinkedIn</a>
